### ISSUE TITLE
Need i create a new branch to commit my changed project?

### ISSUE THREAD

**Issue by WonderSeven** [PasaLab/MR-Course-Assignments#1]
Could i use the master branch to commit my changes? Now i have created a new branch and commit the changes to my own github repository. And i shall create a pull request, but i don't konw whether it is right.

**Comment by newnius** [comment]
You'd better checkout to a new branch in your own repo, and make changes on that branch. Then make a PR to the origin project (master branch). Just follow the guide to create that PR.

**Comment by WonderSeven** [comment]
Ok, thanks a lot!
