### ISSUE TITLE
已经签署了cla,为什么还是cla-missing

### ISSUE THREAD

**Issue by GitXiaoZe** [PasaLab/MR-Course-Assignments#102]
(Your NJUID here)
MG1833025
(Your Task link here)
https://github.com/Alluxio/new-contributor-tasks/issues/329
(Describe Your problem briefly here)
助教，我已经在10月25号签署了contribution license agreement.并且已经收到了相关的邮件了，为什么我第一个实验还是cla-missing呢？
(Provide necessary information, as many as you can)

**Comment by newnius** [comment]
按照流程再走一遍吧，应该是缺少了步骤

**Comment by newnius** [comment]
Inactive
