### ISSUE TITLE
https://github.com/Alluxio/alluxio/pull/8116

### ISSUE THREAD

**Issue by GreenPines** [PasaLab/MR-Course-Assignments#108]
(Your NJUID here)

MG1833061

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/391

(Describe Your problem briefly here)
本地运行的结果如下：
Failed tests: 
  TieredIdentityFactoryTest.notExecutable:160 
Expected: a string containing "Permission denied"
     but: was "Failed to run script /tmp/junit619813622337250117/junit7891256956517059620.tmp: java.io.IOException: Cannot run program "/tmp/junit619813622337250117/junit7891256956517059620.tmp": error=13, 权限不够"

Tests run: 576, Failures: 1, Errors: 0, Skipped: 5

[INFO] Alluxio Core - Common Utilities .................... FAILURE [01:46 min]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project alluxio-core-common: There are test failures.
(Provide necessary information, as many as you can)
Thanks！

**Comment by GreenPines** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/Alluxio-Pull-Request-Builder/955/console
线上的测试log同样显示这个问题
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project alluxio-tests: There are test failures.

**Comment by newnius** [comment]
线上错误是测试超时了，重新发起测试。

线下不太清楚

**Comment by GreenPines** [comment]
@newnius

**Comment by newnius** [comment]
在PR下面回复 `Jenkins, test this please` 就可以了

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/8116/files

你改动了文件的权限

**Comment by GreenPines** [comment]
how should i do now？

**Comment by GreenPines** [comment]
@newnius

**Comment by GreenPines** [comment]
我提交了一个新的pull request，原来的pull request需要关闭吗。新的pull request地址https://github.com/Alluxio/alluxio/pull/8134

**Comment by GreenPines** [comment]
新的pull request已经通过了。腾讯文档之前提交的pull request地址无法修改，我是重新提交一份吗？

**Comment by newnius** [comment]
腾讯文档是用来收集你们的学号的。

旧的PR自己关闭

**Comment by GreenPines** [comment]
助教，你好！我最后没有alluxio-bot 提示我需要sign a contribution license agreement.只有一个提示 alluxio-bot assigned aaudiber an hour ago

**Comment by newnius** [comment]
以前签署过就不需要

**Comment by GreenPines** [comment]
这个以前是指我第一次向alluxio PR吗，我上一次PR的时候也没让我签署这个

**Comment by newnius** [comment]
那就别管他了
