### ISSUE TITLE
MF1833054

### ISSUE THREAD

**Issue by tsdjh** [PasaLab/MR-Course-Assignments#111]
(Your NJUID here)

MF1833054

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/293

(Describe Your problem briefly here)
在alluxio/core/common目录下执行 mvn clean install -DskipTests 之后，显示如下错误，请问如何解决？
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alluxio Core - Common Utilities 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.alluxio:alluxio-core-protobuf:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.447 s
[INFO] Finished at: 2018-11-10T12:16:16+08:00
[INFO] Final Memory: 14M/94M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alluxio-core-common: Could not resolve dependencies for project org.alluxio:alluxio-core-common:jar:2.0.0-SNAPSHOT: Failure to find org.alluxio:alluxio-core-protobuf:jar:2.0.0-SNAPSHOT in http://nexus.qmino.com/content/repositories/miredot was cached in the local repository, resolution will not be reattempted until the update interval of miredot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by newnius** [comment]
跳过本地测试

**Comment by newnius** [comment]
Inactive
