### ISSUE TITLE
Jenkins 即将关闭

### ISSUE THREAD

**Issue by usernamehcx** [PasaLab/MR-Course-Assignments#113]
(Your NJUID here)

MF1833025

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/282

(Describe Your problem briefly here)

我本地测试是过了，但是线上测试的时候，发现Jenkins 即将关闭（无法测试了）,这个我该怎么办

**Comment by newnius** [comment]
哪里有说即将关闭？

**Comment by usernamehcx** [comment]
现在恢复正常了，我刚刚发的时候是没办法测试的。

**Comment by newnius** [comment]
乃们呐，总想搞个大新闻。。。

**Comment by liuhaogui** [comment]
![1588902398401](https://user-images.githubusercontent.com/47664337/81361392-d5c23400-9110-11ea-9364-9d47e78e5d3c.jpg)

As shown in the figure, how to solve it
