### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/7955}}

### ISSUE THREAD

**Issue by menglei5633** [PasaLab/MR-Course-Assignments#117]
(Your NJUID here)

MG1833001

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/332 

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/7992

**Comment by newnius** [comment]
What is your NJUID and Task Link?

**Comment by menglei5633** [comment]
my NJUID is MF1833048

**Comment by menglei5633** [comment]
my PR link is https://github.com/Alluxio/alluxio/pull/7955
