### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8099}}

### ISSUE THREAD

**Issue by 15091444119** [PasaLab/MR-Course-Assignments#119]
(Your NJUID here)

MG1833095

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/359

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8099

**Comment by 15091444119** [comment]
what's wrong with this issue？

**Comment by newnius** [comment]
Everything is OK.

Will be handled after the DDL

**Comment by 15091444119** [comment]
Thanks!
