### ISSUE TITLE
DZ1833004 董绍康

### ISSUE THREAD

**Issue by DSKtwilight** [PasaLab/MR-Course-Assignments#127]
(Your NJUID here)

DZ1833004

(Your Task link here)

https://github.com/Alluxio/alluxio/pull/8020

(Describe Your problem briefly here)

助教您好，我之前也一直反应这个问题，测试显示通过，Merge build finished。发送过来的签署邮件也已经签署完毕很多次（如下图），但是Pull Request仍然是Open，麻烦您了。

![image](https://user-images.githubusercontent.com/35372722/49418209-fec3f400-f7bb-11e8-9cf4-fa8bdce5f3d1.png)
![image](https://user-images.githubusercontent.com/35372722/49418219-0c797980-f7bc-11e8-83f3-c8ec66eedc40.png)
![image](https://user-images.githubusercontent.com/35372722/49418228-1a2eff00-f7bc-11e8-9a5f-642bafa8b943.png)

**Comment by newnius** [comment]
1. PR 右边的 `cia-missing`标签没有去掉，说明签署协议没有完成，完成的标准一是标签被去掉，或者是当你再次点击[签署协议链接](https://cla.alluxio.org/status)时提示`completed`而不是`pending`。签署未完成的原因很多，可能没有点击确认邮件等等。

2. 维护者并不认同你所作出的修改，讨论如何修改更加合适，而你没有回复。

**Comment by newnius** [comment]
Inactive
