### ISSUE TITLE
DZ1833027夏培萱

### ISSUE THREAD

**Issue by PeixuanXia** [PasaLab/MR-Course-Assignments#130]
(Your NJUID here)

DZ1833027

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/389

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8175

**Comment by newnius** [comment]
Already recorded, see [54b1f1](https://github.com/PasaLab/MR-Course-Assignments/commit/54b1f1a81b1fbdadc8a0fe3afad51f63ace9b6ef)
