### ISSUE TITLE
404 in installing node version v10.11.0 when validating the code style etc.

### ISSUE THREAD

**Issue by njuxx** [PasaLab/MR-Course-Assignments#132]
161220153

https://github.com/Alluxio/new-contributor-tasks/issues/442

在按照给的说明How-To.md执行到第8步的时候，maven提示failure，失败出现在buildin Alluxio UI中下载node.js的时候。显示是从https://nodejs.org/dist/v10.11.0/node-v10.11.0-linux-x86.tar.gz 这个网址下载，但是这个网址404了，所以失败

[INFO] 
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ alluxio-ui ---
[INFO] Installing node version v10.11.0
[INFO] Downloading https://nodejs.org/dist/v10.11.0/node-v10.11.0-linux-x86.tar.gz to /home/njuxx/.m2/repository/com/github/eirslett/node/10.11.0/node-10.11.0-linux-x86.tar.gz
...
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project alluxio-ui: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

请问助教要怎么解决这个问题呢？

**Comment by newnius** [comment]
如果你能保证自己的修改没有太大问题，可以跳过test，直接提交pr，看在线测试的结果

**Comment by njuxx** [comment]
那这个在以后的作业里也不会产生影响吗？

**Comment by newnius** [comment]
什么意思？
本地测试不是必需的，只要结果正确就行

**Comment by njuxx** [comment]
好的，谢谢助教
