### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8620}}

### ISSUE THREAD

**Issue by Dreamanne** [PasaLab/MR-Course-Assignments#153]
(Your NJUID here)

161220092

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/401

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8620

**Comment by newnius** [comment]
alluxio 社区在改版，我也不知道他们后面要怎么搞。

这个算你过了
