### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8702}}

### ISSUE THREAD

**Issue by GiantSeaweed** [PasaLab/MR-Course-Assignments#155]
(Your NJUID here)

161220039

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/494

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8702

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/8702/files

你多加了一个文件，把这个删掉
