### ISSUE TITLE
PR reaquest

### ISSUE THREAD

**Issue by foreveryounth** [PasaLab/MR-Course-Assignments#169]
(Your NJUID here)

161220178

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/459

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8764

**Comment by newnius** [comment]
cia-missing

PR title follows the conventions: FAIL

    The title of the PR does not pass all the checks. Please fix the following issues:
        First word must be capitalized
        First word of title ("small") is not an imperative verb. Please use one of the valid words

**Comment by foreveryounth** [comment]
allready changed PR-TITLE
              **[SMALLFIX]small fix**
to
              **[SMALLFIX]Supply the name of variable to Preconditions.**
what to do next?

**Comment by newnius** [comment]
PR title follows the conventions: FAIL

    The title of the PR does not pass all the checks. Please fix the following issues:
        Title must not end with punctuation

**Comment by newnius** [comment]
cia-missing

**Comment by foreveryounth** [comment]
Have removed the period

**Comment by foreveryounth** [comment]
仍然没有被merge，还要什么需要修改的吗

**Comment by newnius** [comment]
cia-missing
