### ISSUE TITLE
Failed 

### ISSUE THREAD

**Issue by AlexisCoke** [PasaLab/MR-Course-Assignments#175]
(Your NJUID here)

161220123

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/417

(Describe Your problem briefly here)

本地编译报错信息如下：
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project alluxio-core-server-master: Failed during checkstyle execution: There is 1 error reported by Checkstyle 6.11.2 with /home/jingtao/alluxio/build/checkstyle/alluxio_checks.xml ruleset. -> [Help 1]

检查过后发现单行并没有超过100字符，想请教助教问题出在哪里了？

**Comment by newnius** [comment]
没有看到关键信息

**Comment by AlexisCoke** [comment]
按照task里面用lambda表达式替换了之后，本地编译无法通过，经检查多遍，且多次修改code style都无法编译成功。

**Comment by newnius** [comment]
> /usr/src/alluxio/core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java:84:8: error: Unused import - com.codahale.metrics.MetricFilter.

**Comment by newnius** [comment]
Inactive
