### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8799}}

### ISSUE THREAD

**Issue by MhDang** [PasaLab/MR-Course-Assignments#181]
(Your NJUID here)

161220030

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/489

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8799

**Comment by newnius** [comment]
Uncesseay file
https://github.com/Alluxio/alluxio/pull/8799/files

**Comment by MhDang** [comment]
@newnius Thanks for pointing it out. The bug has been fixed.
