### ISSUE TITLE
a question about PR

### ISSUE THREAD

**Issue by Draculair** [PasaLab/MR-Course-Assignments#183]
(Your NJUID here)
161220102
(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/402

(Describe Your problem briefly here)
I want to ask whether only thing I can do after create a PR and all checks have passed is just waiting

(Provide necessary information, as many as you can)
like this
All checks have passed
2 successful checks
@alluxio-bot
PR-EMAIL — Email looks good!
@alluxio-bot
PR-TITLE — Title looks good!
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by newnius** [comment]
```
[Java](Java-Setup.html)(JDK 8或更高版本)
```
is a standard markdown syntax and do not modify it.

**And**, please remove the uncessary file

https://github.com/Alluxio/alluxio/pull/8801/files

**Comment by Draculair** [comment]
excuse me, I want to know whether the step "mvn clean install -DskipTests" is an essential step even when I only made some tiny change cause it's really a step taking so many time

**Comment by newnius** [comment]
It is optional

**Comment by Draculair** [comment]
thx for answer, and I'm sry that but am I all right now?

**Comment by newnius** [comment]
Well, `{{site.ALLUXIO_RELEASED_VERSION}}` is also a markdown syntax and so is `[FAQ](#faq)` etc.

**Comment by Draculair** [comment]
sry, but why it shows test fail and https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-Pull-Request-Builder/2945/
I can't get some useful information from this link

**Comment by newnius** [comment]
This is also a command `alluxio ALL=(ALL)`

**Comment by newnius** [comment]
And remove the uncessary file, please.

**Comment by Draculair** [comment]
excuse me, I've got a problem that"@Draculair thanks for improving the doc. Can you revert the changes to npm-shrinkwrap.json?" but I didn't change this file at all. So I suppose its change is related to my change of md file, and if so, how can I change the md file without changing the json file

**Comment by newnius** [comment]
It is accidently generated by your IDE or the tests. Just delete is and commit + push again.

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/8801/
