### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8920}}

### ISSUE THREAD

**Issue by Echoes-Feng** [PasaLab/MR-Course-Assignments#184]
(Your NJUID here)

161180034

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/542

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8920

**Comment by newnius** [comment]
Uncessary file https://github.com/Alluxio/alluxio/pull/8802/files
