### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8651}}

### ISSUE THREAD

**Issue by oooooverflow** [PasaLab/MR-Course-Assignments#186]
(Your NJUID here)

MG1833001

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/332 

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/7992

**Comment by newnius** [comment]
Please provide your own PR link.

**Comment by newnius** [comment]
Duplicate https://github.com/PasaLab/MR-Course-Assignments/issues/193
