### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8922}}

### ISSUE THREAD

**Issue by mana-wrym** [PasaLab/MR-Course-Assignments#217]
(Your NJUID here)

161220051

(Your Task link here)

Alluxio/new-contributor-tasks/issues/502

(Your PR link here)

Alluxio/alluxio/pull/8922

**Comment by newnius** [comment]
`cia-missing` && `unnecessary file` https://github.com/Alluxio/alluxio/pull/8922/files

**Comment by newnius** [comment]
TLE
