### ISSUE TITLE
[ERROR] Java 8 migration: replace anonymous type with lambda in alluxio.web.WebInterfaceWorkerMetricsServlet#populateValues #326

### ISSUE THREAD

**Issue by dymmmmm** [PasaLab/MR-Course-Assignments#22]
助教您好，我的作业是326，其中有一段，需要将
Map<String, Counter> counters = mr.getCounters(new MetricFilter() {
      @Override
      public boolean matches(String name, Metric metric) {
        return !(name.endsWith("Ops"));
      }
    });
替换为
Map<String, Counter> counters = mr.getCounters((name, metric) -> !(name.endsWith("Ops")));
但是总是编译失败，报错。
我是直接将代码复制粘贴的，还是一直报错。
用源码编译的时候就success，助教，这部分代码替换成这样真的没问题吗？因为我真的不知道怎么改了啊。。。麻烦解答了。。。谢谢。。。

**Comment by newnius** [comment]
你可以改完之后发起pr，再看看自动测试的结果。

你的描述太模糊了

**Comment by dymmmmm** [comment]
这是报错信息。
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Alluxio Parent ..................................... SUCCESS [ 11.701 s]
[INFO] Alluxio Core ....................................... SUCCESS [  3.131 s]
[INFO] Alluxio Core - Protobuf ............................ SUCCESS [01:08 min]
[INFO] Alluxio Core - Common Utilities .................... SUCCESS [03:00 min]
[INFO] Alluxio Core - Client .............................. SUCCESS [  1.084 s]
[INFO] Alluxio Core - Client - File System ................ SUCCESS [ 31.555 s]
[INFO] Alluxio Key Value .................................. SUCCESS [  1.153 s]
[INFO] Alluxio Key Value - Common Utilities ............... SUCCESS [ 36.485 s]
[INFO] Alluxio Key Value - Client ......................... SUCCESS [ 15.191 s]
[INFO] Alluxio Key Value - Hadoop Utilities ............... SUCCESS [ 11.445 s]
[INFO] Alluxio Examples ................................... SUCCESS [ 18.101 s]
[INFO] Alluxio Job Service ................................ SUCCESS [  1.111 s]
[INFO] Alluxio Job Service - Common Utilities ............. SUCCESS [ 34.541 s]
[INFO] Alluxio Job Service - Client ....................... SUCCESS [ 13.396 s]
[INFO] Alluxio Shell ...................................... SUCCESS [ 26.421 s]
[INFO] Alluxio Assembly ................................... SUCCESS [  0.979 s]
[INFO] Alluxio Assembly - Client .......................... SUCCESS [  9.126 s]
[INFO] Alluxio Core - Server .............................. SUCCESS [  1.417 s]
[INFO] Alluxio Core - Server - Common Utilities ........... SUCCESS [ 33.495 s]
[INFO] Alluxio Under File System .......................... SUCCESS [  1.341 s]
[INFO] Alluxio Under File System - Local FS ............... SUCCESS [ 11.550 s]
[INFO] Alluxio Core - Server - Master ..................... SUCCESS [01:02 min]
[INFO] Alluxio Core - Server - Proxy ...................... SUCCESS [ 19.542 s]
[INFO] Alluxio Core - Server - Worker ..................... FAILURE [  2.487 s]
[INFO] Alluxio Job Service - Server ....................... SKIPPED
[INFO] Alluxio Key Value - Server ......................... SKIPPED
[INFO] Alluxio Log Server ................................. SKIPPED
[INFO] Alluxio Assembly - Server .......................... SKIPPED
[INFO] Alluxio Core - Client - HDFS ....................... SKIPPED
[INFO] Alluxio Core - Client - Runtime .................... SKIPPED
[INFO] Alluxio Integration ................................ SKIPPED
[INFO] Alluxio Integration - Checker ...................... SKIPPED
[INFO] Alluxio Integration - FUSE ......................... SKIPPED
[INFO] Alluxio MiniCluster ................................ SKIPPED
[INFO] Alluxio Tests ...................................... SKIPPED
[INFO] Alluxio Under File System - Tencent Cloud COS ...... SKIPPED
[INFO] Alluxio Under File System - GCS .................... SKIPPED
[INFO] Alluxio Under File System - HDFS ................... SKIPPED
[INFO] Alluxio Under File System - Aliyun OSS ............. SKIPPED
[INFO] Alluxio Under File System - S3A .................... SKIPPED
[INFO] Alluxio Under File System - Swift .................. SKIPPED
[INFO] Alluxio Under File System - Microsoft Azure Blob Storage SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:58 min
[INFO] Finished at: 2018-10-13T18:54:43+08:00
[INFO] Final Memory: 130M/791M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project alluxio-core-server-worker: Failed during checkstyle execution: There is 1 error reported by Checkstyle 6.11.2 with /home/dym/alluxio/build/checkstyle/alluxio_checks.xml ruleset. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alluxio-core-server-worker

**Comment by newnius** [comment]
这个是代码风格问题，具体的出错原因在前面，你没有贴出来。

请检查以下几点

1、代码缩进
2、单行代码是否超过100字符
