### ISSUE TITLE
Merged build finished. Test FAILed.

### ISSUE THREAD

**Issue by xlx-nju** [PasaLab/MR-Course-Assignments#23]
https://github.com/Alluxio/alluxio/pull/7972
MF1833082
任务是：
Replace

      StringBuffer sSum = new StringBuffer();

with

      StringBuilder sSum = new StringBuilder();
本地是build success的，不知道为什么提交后就Test Failed的了。

**Comment by newnius** [comment]
Now, it PASSed.
