### ISSUE TITLE
{{https://github.com/Alluxio/alluxio/pull/8972}}

### ISSUE THREAD

**Issue by Logarithm5314** [PasaLab/MR-Course-Assignments#234]
(Your NJUID here)

161220041

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/496

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8972

**Comment by newnius** [comment]
Not all methods would return null.

**Comment by Logarithm5314** [comment]
> 
> 
> Not all methods would return null.

Already removed @Nullable annotations on void functions.
Plz check again.
