### ISSUE TITLE
{{https://github.com/Alluxio/new-contributor-tasks/issues/457}}

### ISSUE THREAD

**Issue by yuyutai** [PasaLab/MR-Course-Assignments#261]
(Your NJUID here)

161220176

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/457

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/9032

**Comment by newnius** [comment]
<img width="500" alt="Screen Shot 2019-05-11 at 2 49 16 PM" src="https://user-images.githubusercontent.com/11253412/57566161-fc656600-73fb-11e9-8d1f-ac6d8b573b71.png">

**Comment by yuyutai** [comment]
老师，错误已经修正

**Comment by yuyutai** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/48487673/57567790-29704380-7411-11e9-855c-4e6b86b91cf0.png">
