### ISSUE TITLE
文件alluxio-ui/npm-shrinkwrap.json出现不明变动

### ISSUE THREAD

**Issue by snowhealing** [PasaLab/MR-Course-Assignments#267]
(Your NJUID here)

161220040

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/495

(Describe Your problem briefly here)

文件alluxio-ui/npm-shrinkwrap.json未被我手动修改，在提交至远程仓库提交PR后，提示该文件出现冲突 查看文件变化，显示该文件出现不明更改，请问出现这个问题的原因是什么 需要如何修改
PRlink为 https://github.com/Alluxio/alluxio/pull/9055

**Comment by newnius** [comment]
可能是 IDE 自动生成的，删掉即可

**Comment by newnius** [comment]
Duplicate https://github.com/PasaLab/MR-Course-Assignments/issues/266
