### ISSUE TITLE
作业添加

### ISSUE THREAD

**Issue by deggg** [PasaLab/MR-Course-Assignments#287]
(Your NJUID here)

151220067

(Your Task link here)

(Describe Your problem briefly here)
老师你好，我是重修这门课程的学生，（151220067罗吉），任务列表中没有我的学号，请问现在还能添加吗。谢谢。

(Provide necessary information, as many as you can)

**Comment by newnius** [comment]
名单是从课程网站选课列表里导出的，你补选课之后，可以再添加。

**Comment by deggg** [comment]
助教你好，课程网站上已经有我的名单了，可以在实验一的任务列表中将我的任务添加上去吗。谢谢。

**Comment by newnius** [comment]
已添加
