### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by deggg** [PasaLab/MR-Course-Assignments#288]
(Your NJUID here)

151220067

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/560

(Describe Your problem briefly here)
pull request后回复了一条test failed，我没有找到原因。

(Provide necessary information, as many as you can)
https://github.com/Alluxio/alluxio/pull/9172

**Comment by newnius** [comment]
/usr/src/alluxio/core/common/src/test/java/alluxio/wire/BlockLocationTest.java:15: error: 'alluxio.util.CommonUtils' should be separated from previous import group.
