### ISSUE TITLE
PR的Test Failed后，多久会重新测试呢？

### ISSUE THREAD

**Issue by Kael-Chan** [PasaLab/MR-Course-Assignments#31]
push新改动到对应分支后，需要额外的操作吗？

**Comment by Kael-Chan** [comment]
我在`Jenkins`上看到了测试状态，是另外的原因导致没有测试结果的。

状态：(pending—Jenkins is about to shut down)

看起来每次发生修改那边都会自动做一次Test.

**Comment by newnius** [comment]
可以用

```
Jenkins, test this please
```

来手动发起测试

**Comment by Kael-Chan** [comment]
谢谢～
