### ISSUE TITLE
build success ,Test failed

### ISSUE THREAD

**Issue by luzhouxiaobai** [PasaLab/MR-Course-Assignments#32]
助教：
您好！
MF1833098
[Alluxio/alluxio#7981](https://github.com/Alluxio/alluxio/pull/7981)
任务是：
Replace

      if (part1 == part2) {
        return 0;
      }
      if (part1 < part2) {
        return -1;
      }
      return 1;
with

      return Long.compare(part1, part2);
在本地测试的时候是build success，提交之后的结果为test failed

**Comment by newnius** [comment]
极少数情况下测试平台比较繁忙，会超时，手动发起重测
