### ISSUE TITLE
Merged build finished. Test FAILed.

### ISSUE THREAD

**Issue by MoxinC** [PasaLab/MR-Course-Assignments#44]
MG1833001

https://github.com/Alluxio/new-contributor-tasks/issues/332 

任务是：
Replace
```
      Ordering.natural().onResultOf(new Function<UIFileInfo, Comparable<String>>() {
        @Override
        public Comparable<String> apply(UIFileInfo input) {
          return input.mAbsolutePath;
        }
      });
```
with
```
      Ordering.natural().onResultOf((Function<UIFileInfo, Comparable<String>>) input -> input.mAbsolutePath);
```

问题是：
Merged build finished. Test FAILed.
看之前的 issue 有提到每行代码的最大长度的问题，也尝试了多换几行，但是还是出现同样的问题。

PR 地址：
https://github.com/Alluxio/alluxio/pull/8002

**Comment by gitforsunyuhu** [comment]
换行之后，要保证第二行的留空为8个或者10个英文空格~希望对你有帮助。

**Comment by newnius** [comment]
直接用idea的自动换行功能即可

**Comment by MoxinC** [comment]
试了 idea 的自动换行，也是 Test FAILed.
![image](https://user-images.githubusercontent.com/20139119/47201802-abcde300-d3ad-11e8-8c38-559c4b4a4779.png)

另外好像有人（"apc999"）在我的 PR 下也提交了修改，但是也是 Test FAILed.
![image](https://user-images.githubusercontent.com/20139119/47201891-00715e00-d3ae-11e8-8156-27b4e91d20d9.png)

![image](https://user-images.githubusercontent.com/20139119/47201902-09fac600-d3ae-11e8-8817-88f5e0b87950.png)

**Comment by MoxinC** [comment]
协议签署了，Jenkins 测试也 pass 了，但是一直没有 merge 成功的消息。

![2018-10-23_130235](https://user-images.githubusercontent.com/20139119/47336896-1e97d080-d6c4-11e8-820a-1c78b0106e2e.png)

**Comment by newnius** [comment]
AT 一下  apc999

**Comment by MoxinC** [comment]
![image](https://user-images.githubusercontent.com/20139119/47431226-fa281b00-d7cd-11e8-8299-3fbec42f5e9a.png)

没有进展

**Comment by MoxinC** [comment]
![image](https://user-images.githubusercontent.com/20139119/47616807-856e1d00-dafc-11e8-9057-8da6d52cdce9.png)

PR 现在的状态还是 OPEN，一直没人反馈，我是否需要重新发起 PR 或者做点什么吗？

**Comment by newnius** [comment]
I have no idea 🤷‍♂️

**Comment by MoxinC** [comment]
Done, thx!
