### ISSUE TITLE
Merged build finished. Test FAILed.

### ISSUE THREAD

**Issue by LegenDong** [PasaLab/MR-Course-Assignments#56]
(Your NJUID here)

MG1833016

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/278

(Describe Your problem briefly here)

Merged build finished. Test FAILed.

(Provide necessary information, as many as you can)

给出的[日志](https://amplab.cs.berkeley.edu/jenkins/job/Alluxio-Pull-Request-Builder/782/console)是: 
```
Tests run: 58, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 114.389 sec <<< FAILURE! - in alluxio.client.fs.FileSystemMasterIntegrationTest
deleteDirectoryWithPersistedAndNotPersistedSubfolders(alluxio.client.fs.FileSystemMasterIntegrationTest)  Time elapsed: 2.493 sec  <<< ERROR!
alluxio.exception.AccessControlException: Permission denied: user=test, access=-w-, path=/testFolder: failed at /, inode owner=root, inode group=root, inode mode=rwxr-xr-x
	at alluxio.client.fs.FileSystemMasterIntegrationTest.deleteDirectoryWithPersistedAndNotPersistedSubfolders(FileSystemMasterIntegrationTest.java:463)
```
实际上，我只是改成了lamda表达式的形式 
https://github.com/Alluxio/alluxio/pull/8026/commits/50f3fa470a7bbd3623b86dbe48d9a689661249f7
我的PR是 https://github.com/Alluxio/alluxio/pull/8026

**Comment by newnius** [comment]
测试的时候超时了
