### ISSUE TITLE
https://github.com/CarmenJi/alluxio/tree/smallfix

### ISSUE THREAD

**Issue by CarmenJi** [PasaLab/MR-Course-Assignments#57]
(Your NJUID here)

MF1833031

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/284

(Your PR link here)

https://github.com/CarmenJi/alluxio/tree/smallfix

**Comment by newnius** [comment]
Invalid PR link

Please **RTFM**

**Comment by newnius** [comment]
Duplicate of #58
