### ISSUE TITLE
https://github.com/Alluxio/alluxio/pull/8045

### ISSUE THREAD

**Issue by hxer7963** [PasaLab/MR-Course-Assignments#70]
(Your NJUID here)

MG1833027

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/384

(Your PR link here)

https://github.com/Alluxio/alluxio/pull/8045

PS: PR is merged, but i don't receive a alluxio-bot comment in PR page or a link in email list to sign my code, is there a issue?

**Comment by AaronX121** [comment]
I also have this problem. Here is my PR link (https://github.com/Alluxio/alluxio/pull/8056).

**Comment by newnius** [comment]
Not sure why the alluxio-bot doesn't appear, just ignore it since it is merged.
