### ISSUE TITLE
测试通过但是改动的文件中找不到我改动的内容

### ISSUE THREAD

**Issue by ITdoubleseven** [PasaLab/MR-Course-Assignments#73]
(Your NJUID here)

MF1833024

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/281
我第一次建立了PR后test失败，修改之后没有再建立新的PR测试通过了。但是那个分配的老师说在那个files changed里面找不到我修改过后的文件。只有一个空的.get-credentials和一个submodule。老师建议我建立新的PR。我刚刚重新编译成功后再执行git add . -A之后执行git commit时提示：
位于分支 smallfix
尚未暂存以备提交的变更：
	修改：     alluxio (修改的内容)

修改尚未加入提交
我不知道是哪里错了，请老师帮忙看下。

**Comment by newnius** [comment]
你没按照流程走，第5步clone完之后cd 到项目根目录下，再进行操作。

**Comment by ITdoubleseven** [comment]
> 你没按照流程走，第5步clone完之后cd 到项目根目录下，再进行操作。

我按照您的回复在根目录下进行操作并新建了分支后编译通不过，显示如下error：[ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.9:check (default) on project alluxio-parent: Some files do not have the expected license header -> [Help 1]
之后我百度后执行命令，mvn license:format，显示build success，再次用mvn clean install -DskipTests
编译时又报如下错误：Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (Check that there are no Windows line endings) on project alluxio-parent: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]。

**Comment by newnius** [comment]
不知道你做了什么，改动了文件顶部的版权信息

**Comment by ITdoubleseven** [comment]
那重新clone可以吗

**Comment by newnius** [comment]
你可以删除现有的项目，然后从头开始做，但是别忘了关闭之前提交的PR。

**Comment by ITdoubleseven** [comment]
好的谢谢(*°∀°)=3

----------
day day up.

--------------原始邮件--------------
发件人："newnius "<notifications@github.com>;
发送时间：2018年10月26日(星期五) 中午1:44
收件人："PasaLab/MR-Course-Assignments" <MR-Course-Assignments@noreply.github.com>;
抄送："ITdoubleseven "<mf1833024@smail.nju.edu.cn>;"Author "<author@noreply.github.com>;
主题：Re: [PasaLab/MR-Course-Assignments] 测试通过但是改动的文件中找不到我改动的内容 (#73)
-----------------------------------

 
你可以删除现有的项目，然后从头开始做，但是别忘了关闭之前提交的PR。

**Comment by ITdoubleseven** [comment]
所有重新来过一遍了，在本地编译通过。但是test failed。
