### ISSUE TITLE
unfork了，现在重新fork文件夹下内容都不一样了

### ISSUE THREAD

**Issue by PDSnoW** [PasaLab/MR-Course-Assignments#79]
(Your NJUID here)

MG1833001

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/332 

(Describe Your problem briefly here)

(Provide necessary information, as many as you can)

**Comment by PDSnoW** [comment]
老师您好，我之前按照公告里提供的创建PR的顺序去做，有问题，然后问做过的同学，然后就不知道在哪一步，想重做，然后我就unfork了，现在重新fork文件夹下内容都不一样了，是不是我的任务都没了没法做了？路径不对，但是我还能找到那个文件夹，这样到时候提交任务时没问题吧？

**Comment by newnius** [comment]
明天重新分配

**Comment by PDSnoW** [comment]
> 明天重新分配

老师，就是让改的那个文件夹下面的文件重新组织了，我要修改的文件在重新组的那个文件夹下面，以前是/docs/cn/Client-Python.md现在是/docs/cn/api/lient-Python.md要修改的内容一样，我也已经提交了，merge test 也PASSed了，所以如果我做的正确的，老师能改一下任务描述的内容，我可以不重做吗？

**Comment by newnius** [comment]
如果需要修改的部分还在，就不需要。

你没提供正确的task链接

**Comment by newnius** [comment]
Resolved
