### ISSUE TITLE
Error in validating the code style

### ISSUE THREAD

**Issue by yaoyueduzhen** [PasaLab/MR-Course-Assignments#8]
Error after executing the following command:
mvn clean install -DskipTests

Error details：
[ERROR] GC overhead limit exceeded -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

I have added
export MAVEN_OPTS="-Xms4096m -Xmx4096m -XX:PermSize=1024m -XX:MaxPermSize=1024m"
to the file .bash_profile, but it doesn't work.

How can I solve this problem？
Thank you!

**Comment by newnius** [comment]
It is hard to figure out what is wrong as the information provided is poor.

You can skip the tests and create a PR, the bot will do these tests.

**Comment by newnius** [comment]
#14 

close
