### ISSUE TITLE
我需要改动的是加空格，那边给的反馈是测试通过，但是他们没有加空格的习惯

### ISSUE THREAD

**Issue by wxpy** [PasaLab/MR-Course-Assignments#80]
(Your NJUID here)

MP1833047

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/366

(Describe Your problem briefly here)
我的工作是要加个空格，然后测试通过了，但是那边说他们没有加空格的传统，让重新提交一个PR
 We do not have the convention to add spaces between Chinese words and English words. Could you close this PR and create other PRs? Thanks for your contribution!

(Provide necessary information, as many as you can)

**Comment by newnius** [comment]
那你就按照他们的要求再提交一个 PR 吧。

**Comment by wxpy** [comment]
>           那你就按照他们的要求再提交一个 PR 吧。

那我就随便改动么，还是你重新给个任务。

**Comment by newnius** [comment]
你关闭原来的PR，然后按照格式重新提交啊

**Comment by newnius** [comment]
Inactive
