### ISSUE TITLE
实验要求修改的文件实际不存在

### ISSUE THREAD

**Issue by GreenPines** [PasaLab/MR-Course-Assignments#84]
(Your NJUID here)

MG1833061

(Your Task link here)

https://github.com/Alluxio/new-contributor-tasks/issues/344

(Describe Your problem briefly here)
实验要求修改[DOCFIX] Fix typo in docs/cn/Compatibility.md #344，但是目录下并不存在Compatibility.md文件

(Provide necessary information, as many as you can)

**Comment by newnius** [comment]
Re-assigned

**Comment by newnius** [comment]
@15091444119 Just provide your task url

**Comment by 15091444119** [comment]
https://github.com/Alluxio/new-contributor-tasks/issues/359

**Comment by newnius** [comment]
@15091444119
It has been moved `docs/cn/deploy/Running-Alluxio-on-Mesos.md`.

**Comment by 15091444119** [comment]
Thanks!
