### ISSUE TITLE
[smallfix]experiment 1 task1 : there's no required file in the issue

### ISSUE THREAD

**Issue by lixiawei** [PasaLab/MR-Course-Assignments#86]
MG1833033
 
https://github.com/Alluxio/new-contributor-tasks/issues/363

This dir  docs/cn/Thrift.mddoesn't have the file named Thrift.md .  
Please help me to check it . @newnius

**Comment by newnius** [comment]
What is your NJUID? `MP` or `MG`?

I have re-assigned your task, please take a look.

**Comment by lixiawei** [comment]
@newnius Thanks for ur help.  My ID is Mp1833033 .

**Comment by lixiawei** [comment]
hi for the new assignment https://github.com/Alluxio/new-contributor-tasks/issues/390,I've finished it. But I cannot find my branch "smallfix" in the project. Could you please help me recruit me in the project or which step I may make a mistake? @newnius Thank you .

**Comment by newnius** [comment]
You have to create branch `smallfix` yourself by `git checkout -b smallfix`, which is mentioned in the manual.

**Comment by lixiawei** [comment]
Sorry I just didn't found my smallfix branch . Now this pr https://github.com/Alluxio/alluxio/pull/8104 is waiting to be merged . Please help check.

**Comment by newnius** [comment]
https://github.com/PasaLab/MR-Course-Assignments/blob/fall-2018/Errors.md

Follow the guide, please

**Comment by lixiawei** [comment]
sorry I've closed the pr https://github.com/Alluxio/alluxio/pull/8104,but have someq questions shout the `build result`

**Comment by newnius** [comment]
Alluxio community doesn't welcome issues in GitHub

**Comment by newnius** [comment]
Inactive
